name: JS Upgrade

on:
  # TODO: cron instead of push
  push:
    branches:
      - 4

jobs:
  jsupgrade:
    uses: emteknetnz/github-actions-ci-cd/.github/workflows/update-js-deps.yml@pulls/main/update-js-deps

# Trigger workflow ..
  
